services:
* type: web
  name: now-playing-server
  runtime: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn main:app -b 0.0.0.0:10000"
  envVars:
  * key: PORT
    value: 10000
